<?xml version="1.0" encoding="utf-8"?><Database Name="Supervisor" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-U6J54HF;Initial Catalog=Supervisor;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="MartivaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tabla_Busqueda_De_Ejercicios_Por_Etiquetas" Member="Tabla_Busqueda_De_Ejercicios_Por_Etiquetas">
    <Type Name="Tabla_Busqueda_De_Ejercicios_Por_Etiquetas">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Busqueda_Profesor" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Etiqueta_Busqueda_Ano" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Etiqueta_Busqueda_Colegio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Etiqueta_Busqueda_Materia" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Etiqueta_Busqueda_Tema" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Busqueda_De_Ejercicios_Por_Etiquetas" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Ubicacion_De_Los_Ejercicios" Member="Tabla_Ubicacion_De_Los_Ejercicios">
    <Type Name="Tabla_Ubicacion_De_Los_Ejercicios">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ubicacion_Respuesta_Imprimible" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Ubicacion_Respuesta_Visible" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Ubicacion_Videos_Y_Explicaciones" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Ubicacion_De_Los_Ejercicios" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Datos_De_Usuarios" Member="Tabla_Datos_De_Usuarios">
    <Type Name="Tabla_Datos_De_Usuarios">
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_De_Skype" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Numero_De_Celular" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Modelo_De_Celular" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Tabla_De_Usuarios_Tabla_Datos_De_Usuarios" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Datos_Extra_De_Usuarios" Member="Tabla_Datos_Extra_De_Usuarios">
    <Type Name="Tabla_Datos_Extra_De_Usuarios">
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Alta" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Usuarios_Tabla_Datos_Extra_De_Usuarios" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Administradores" Member="Tabla_De_Administradores">
    <Type Name="Tabla_De_Administradores">
      <Column Name="ID_Administrador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Administrador" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Administrador_Bloqueado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PI_Address" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Tabla_De_Administradores_Tabla_De_Comentario_De_Administradores" Member="Tabla_De_Comentario_De_Administradores" ThisKey="ID_Administrador" OtherKey="ID_Administrador" Type="Tabla_De_Comentario_De_Administradores" />
      <Association Name="Tabla_De_Administradores_Tabla_De_Control_De_Administradores" Member="Tabla_De_Control_De_Administradores" ThisKey="ID_Administrador" OtherKey="ID_Administrador" Type="Tabla_De_Control_De_Administradores" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Administradores" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Anos" Member="Tabla_De_Anos">
    <Type Name="Tabla_De_Anos" Id="ID1">
      <Column Name="ID_Ano" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ano" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Ano" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Colegios" Member="Tabla_De_Colegios">
    <Type Name="Tabla_De_Colegios" Id="ID2">
      <Column Name="ID_Colegio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Colegio" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Colegio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Comentario_De_Administradores" Member="Tabla_De_Comentario_De_Administradores">
    <Type Name="Tabla_De_Comentario_De_Administradores">
      <Column Name="ID_Comentario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Administrador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Comentario_Realizado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Administradores_Tabla_De_Comentario_De_Administradores" Member="Tabla_De_Administradores" ThisKey="ID_Administrador" OtherKey="ID_Administrador" Type="Tabla_De_Administradores" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Comentario_De_Usuarios" Member="Tabla_De_Comentario_De_Usuarios">
    <Type Name="Tabla_De_Comentario_De_Usuarios">
      <Column Name="ID_Comentario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Comentario_De_Usuarios" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Control_De_Administradores" Member="Tabla_De_Control_De_Administradores">
    <Type Name="Tabla_De_Control_De_Administradores">
      <Column Name="ID_Ingreso_Egreso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Administrador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Ingreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha_De_Egreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Administradores_Tabla_De_Control_De_Administradores" Member="Tabla_De_Administradores" ThisKey="ID_Administrador" OtherKey="ID_Administrador" Type="Tabla_De_Administradores" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Credito_De_Los_Usuarios" Member="Tabla_De_Credito_De_Los_Usuarios">
    <Type Name="Tabla_De_Credito_De_Los_Usuarios">
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Credito_De_Usuario" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Prestamo_Real_Al_Usuario" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Pedido_De_Prestamo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Bonificacion_Por_Recarga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Usuarios_Tabla_De_Credito_De_Los_Usuarios" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Descripcion_De_Movimientos" Member="Tabla_De_Descripcion_De_Movimientos">
    <Type Name="Tabla_De_Descripcion_De_Movimientos">
      <Column Name="ID_Descripcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion_De_Movimiento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Descripcion_De_Movimientos_Tabla_De_Movimientos" Member="Tabla_De_Movimientos" ThisKey="ID_Descripcion" OtherKey="ID_Descripcion" Type="Tabla_De_Movimientos" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Descripcion_De_Oferta" Member="Tabla_De_Descripcion_De_Oferta">
    <Type Name="Tabla_De_Descripcion_De_Oferta">
      <Column Name="ID_Oferta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion_De_Oferta" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Ejercicios" Member="Tabla_De_Ejercicios">
    <Type Name="Tabla_De_Ejercicios" Id="ID6">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Tipo_De_Ejercicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Tipo_De_Institucion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Explicacion_Realizada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Busqueda_De_Ejercicios_Por_Etiquetas" Member="Tabla_Busqueda_De_Ejercicios_Por_Etiquetas" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_Busqueda_De_Ejercicios_Por_Etiquetas" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Ubicacion_De_Los_Ejercicios" Member="Tabla_Ubicacion_De_Los_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_Ubicacion_De_Los_Ejercicios" />
      <Association Name="Tabla_De_Ejercicios_Tabla_MATH_De_Ejercicios" Member="Tabla_MATH_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_MATH_De_Ejercicios" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Mis_Ejercicios" Member="Tabla_Mis_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_Mis_Ejercicios" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Mis_Explicaciones" Member="Tabla_Mis_Explicaciones" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_Mis_Explicaciones" />
      <Association Name="Tabla_De_Ejercicios_Tabla_De_Explicaciones_Pedidas" Member="Tabla_De_Explicaciones_Pedidas" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Explicaciones_Pedidas" />
      <Association Name="Tabla_Tipo_De_Institucion_Tabla_De_Ejercicios" Member="Tabla_Tipo_De_Institucion" ThisKey="ID_Tipo_De_Institucion" OtherKey="ID_Tipo_De_Institucion" Type="Tabla_Tipo_De_Institucion" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Tabla_Tipo_De_Producto_Tabla_De_Ejercicios" Member="Tabla_Tipo_De_Producto" ThisKey="ID_Tipo_De_Ejercicio" OtherKey="ID_Tipo_De_Ejercicio" Type="Tabla_Tipo_De_Producto" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Empresas" Member="Tabla_De_Empresas">
    <Type Name="Tabla_De_Empresas">
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Administradores" Member="Tabla_De_Administradores" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Administradores" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Comentario_De_Usuarios" Member="Tabla_De_Comentario_De_Usuarios" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Comentario_De_Usuarios" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Precios" Member="Tabla_De_Precios" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Precios" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Tarjetas_Prepagas" Member="Tabla_De_Tarjetas_Prepagas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Tarjetas_Prepagas" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Usuarios" Member="Tabla_De_Usuarios" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Usuarios" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Activacion_De_Ofertas" Member="Tabla_De_Activacion_De_Ofertas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Activacion_De_Ofertas" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Ofertas" Member="Tabla_De_Ofertas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Ofertas" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_IP_Bloqueadas" Member="Tabla_De_IP_Bloqueadas">
    <Type Name="Tabla_De_IP_Bloqueadas">
      <Column Name="ID_Bloqueo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Bloqueo_IP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Materias" Member="Tabla_De_Materias">
    <Type Name="Tabla_De_Materias" Id="ID3">
      <Column Name="ID_Materia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Materia" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Movimientos" Member="Tabla_De_Movimientos">
    <Type Name="Tabla_De_Movimientos">
      <Column Name="ID_Movimiento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Descripcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Del_Movimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Plata_Debe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Plata_Haber" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Tabla_De_Descripcion_De_Movimientos_Tabla_De_Movimientos" Member="Tabla_De_Descripcion_De_Movimientos" ThisKey="ID_Descripcion" OtherKey="ID_Descripcion" Type="Tabla_De_Descripcion_De_Movimientos" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Tabla_De_Usuarios_Tabla_De_Movimientos" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Precios" Member="Tabla_De_Precios">
    <Type Name="Tabla_De_Precios">
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Ejercicio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Explicacion" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Video" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Conjunto_De_Videos" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Explicacion_Personalizada" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Video_Personalizado" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Ejercicio_Personalizado" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Impresion" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Valor_Prestamo_SOS" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Duracion_De_Los_Videos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Duracion_De_Los_Ejercicios_Y_Las_Explicaciones" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Precios" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Profesores" Member="Tabla_De_Profesores">
    <Type Name="Tabla_De_Profesores" Id="ID4">
      <Column Name="ID_Profesor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Profesor" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Profesor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Tarjetas_Prepagas" Member="Tabla_De_Tarjetas_Prepagas">
    <Type Name="Tabla_De_Tarjetas_Prepagas">
      <Column Name="ID_Tarjeta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Credito" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Activacion_De_La_Tarjeta" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Tarjetas_Prepagas" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Temas" Member="Tabla_De_Temas">
    <Type Name="Tabla_De_Temas" Id="ID5">
      <Column Name="ID_Tema" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tema" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Etiqueta_Tema" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Usuarios" Member="Tabla_De_Usuarios">
    <Type Name="Tabla_De_Usuarios">
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activacion_De_Usuarios" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Usuarios_Tabla_Datos_De_Usuarios" Member="Tabla_Datos_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_Datos_De_Usuarios" />
      <Association Name="Tabla_De_Usuarios_Tabla_Datos_Extra_De_Usuarios" Member="Tabla_Datos_Extra_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_Datos_Extra_De_Usuarios" />
      <Association Name="Tabla_De_Usuarios_Tabla_De_Credito_De_Los_Usuarios" Member="Tabla_De_Credito_De_Los_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Credito_De_Los_Usuarios" />
      <Association Name="Tabla_De_Usuarios_Tabla_De_Movimientos" Member="Tabla_De_Movimientos" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Movimientos" />
      <Association Name="Tabla_De_Usuarios_Tabla_Mis_Ejercicios" Member="Tabla_Mis_Ejercicios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_Mis_Ejercicios" />
      <Association Name="Tabla_De_Usuarios_Tabla_Mis_Explicaciones" Member="Tabla_Mis_Explicaciones" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_Mis_Explicaciones" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Usuarios" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_MATH_De_Ejercicios" Member="Tabla_MATH_De_Ejercicios">
    <Type Name="Tabla_MATH_De_Ejercicios" Id="ID7">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Enunciado_MATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Enunciado_Limpio" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tabla_De_Ejercicios_Tabla_MATH_De_Ejercicios" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Mis_Ejercicios" Member="Tabla_Mis_Ejercicios">
    <Type Name="Tabla_Mis_Ejercicios">
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ejercicio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Explicacion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Mis_Ejercicios" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Tabla_De_Usuarios_Tabla_Mis_Ejercicios" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Mis_Explicaciones" Member="Tabla_Mis_Explicaciones">
    <Type Name="Tabla_Mis_Explicaciones">
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Ejercicios_Tabla_Mis_Explicaciones" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Tabla_De_Usuarios_Tabla_Mis_Explicaciones" Member="Tabla_De_Usuarios" ThisKey="ID_Usuario" OtherKey="ID_Usuario" Type="Tabla_De_Usuarios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Tipo_De_Institucion" Member="Tabla_Tipo_De_Institucion">
    <Type Name="Tabla_Tipo_De_Institucion">
      <Column Name="ID_Tipo_De_Institucion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo_De_Institucion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_Tipo_De_Institucion_Tabla_De_Ejercicios" Member="Tabla_De_Ejercicios" ThisKey="ID_Tipo_De_Institucion" OtherKey="ID_Tipo_De_Institucion" Type="Tabla_De_Ejercicios" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_Tipo_De_Producto" Member="Tabla_Tipo_De_Producto">
    <Type Name="Tabla_Tipo_De_Producto">
      <Column Name="ID_Tipo_De_Ejercicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo_De_Producto" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_Tipo_De_Producto_Tabla_De_Ejercicios" Member="Tabla_De_Ejercicios" ThisKey="ID_Tipo_De_Ejercicio" OtherKey="ID_Tipo_De_Ejercicio" Type="Tabla_De_Ejercicios" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_De_Movimientos_De_Usuarios" Member="Vista_De_Movimientos_De_Usuarios">
    <Type Name="Vista_De_Movimientos_De_Usuarios">
      <Column Name="ID_Movimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_De_Movimiento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Del_Movimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Plata_Debe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Plata_Haber" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_Panel_De_Control_Del_Usuario" Member="Vista_Panel_De_Control_Del_Usuario">
    <Type Name="Vista_Panel_De_Control_Del_Usuario">
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activacion_De_Usuarios" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_De_Skype" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Numero_De_Celular" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Modelo_De_Celular" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_De_Alta" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Activacion_De_Ofertas" Member="Tabla_De_Activacion_De_Ofertas">
    <Type Name="Tabla_De_Activacion_De_Ofertas">
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_3" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_4" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_5" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_6" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_7" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_8" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_9" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_10" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_11" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_12" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_13" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_14" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Oferta_15" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Activacion_De_Ofertas" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Ofertas" Member="Tabla_De_Ofertas">
    <Type Name="Tabla_De_Ofertas">
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bonificacion_Por_Registrarse" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Bonificacion_En_La_Proxima_Recarga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descuento_2_Compra" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Descuento_Por_Compra" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Bonificacion_Por_Carga" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Otro_Igual_Gratis" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dos_Por_Uno_En_Video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dos_Por_Uno_En_Ejercicios" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Aumenta_Duracion_Todo_Lo_Comprado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Aumenta_Duracion_De_La_Compra_Actual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gratis" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad_X_Para_Bonificacion_Por_Consultas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bonificacion_Por_X_Consulta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dos_Por_Uno_En_Impresiones" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dos_Por_Uno_En_Explicaciones" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Empresas_Tabla_De_Ofertas" Member="Tabla_De_Empresas" ThisKey="ID_Empresa" OtherKey="ID_Empresa" Type="Tabla_De_Empresas" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Ejercicios_Personalizados_Pedidos" Member="Tabla_De_Ejercicios_Personalizados_Pedidos">
    <Type Name="Tabla_De_Ejercicios_Personalizados_Pedidos">
      <Column Name="ID_Pedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Archivo_Adjunto" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Archivo_Ficha" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Archivo_Enunciado" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Explicacion_Pedida" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ejercicio_Pedido" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Administrador" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Realizado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Duracion_Del_Producto_Al_Comprarlo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Pedido" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_Mis_Ejercicios" Member="Vista_Mis_Ejercicios">
    <Type Name="Vista_Mis_Ejercicios">
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ejercicio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Explicacion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_Mis_Explicaciones" Member="Vista_Mis_Explicaciones">
    <Type Name="Vista_Mis_Explicaciones">
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tabla_De_Explicaciones_Pedidas" Member="Tabla_De_Explicaciones_Pedidas">
    <Type Name="Tabla_De_Explicaciones_Pedidas">
      <Column Name="ID_Consulta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Pedido" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Administrador" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Realizado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Tabla_De_Ejercicios_Tabla_De_Explicaciones_Pedidas" Member="Tabla_De_Ejercicios" ThisKey="ID_Ejercicio" OtherKey="ID_Ejercicio" Type="Tabla_De_Ejercicios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Buscar_En_Tabla_Anos" Method="Buscar_En_Tabla_Anos">
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.Buscar_En_Tabla_Colegios" Method="Buscar_En_Tabla_Colegios">
    <Parameter Name="Colegio" Parameter="colegio" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.Buscar_En_Tabla_Materias" Method="Buscar_En_Tabla_Materias">
    <Parameter Name="Materia" Parameter="materia" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.Buscar_En_Tabla_Profesores" Method="Buscar_En_Tabla_Profesores">
    <Parameter Name="Profesor" Parameter="profesor" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.Buscar_En_Tabla_Temas" Method="Buscar_En_Tabla_Temas">
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.Aclarar_En_La_Tabla_De_Movimiento_La_Extension_De_La_Duracion_De_Los_Productos" Method="Aclarar_En_La_Tabla_De_Movimiento_La_Extension_De_La_Duracion_De_Los_Productos">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Descripcion" Parameter="iD_Descripcion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Activar_Usuario" Method="Activar_Usuario">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Actualizar_El_Panel_De_Control" Method="Actualizar_El_Panel_De_Control">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Numero_De_Celular" Parameter="numero_De_Celular" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Usuario_De_Skype" Parameter="usuario_De_Skype" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Modelo_De_Celular" Parameter="modelo_De_Celular" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Actualizar_La_Duracion_En_La_Lista_Mis_Ejercicios" Method="Actualizar_La_Duracion_En_La_Lista_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dias_Que_Restan_Para_Usar_El_Producto" Parameter="dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Armar_El_Nombre_Del_Archivo_Numero_De_Consultas" Method="Armar_El_Nombre_Del_Archivo_Numero_De_Consultas">
    <Parameter Name="Consultas" Parameter="consultas" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Buscar_Ubicacion_De_La_Respuesta_De_Los_Ejercicios" Method="Buscar_Ubicacion_De_La_Respuesta_De_Los_Ejercicios">
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ubicacion_Respuesta_Visible" Parameter="ubicacion_Respuesta_Visible" Type="System.String" DbType="NVarChar(40)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Loguear_Usuario" Method="Loguear_Usuario">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Buscar_Ubicacion_De_La_Respuesta_Del_Ejercicio_Imprimible" Method="Buscar_Ubicacion_De_La_Respuesta_Del_Ejercicio_Imprimible">
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ubicacion_Respuesta_Imprimible" Parameter="ubicacion_Respuesta_Imprimible" Type="System.String" DbType="NVarChar(40)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Buscar_Ubicacion_De_Los_Videos" Method="Buscar_Ubicacion_De_Los_Videos">
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ubicacion_Videos_Y_Explicaciones" Parameter="ubicacion_Videos_Y_Explicaciones" Type="System.String" DbType="NVarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Cargar_Credito_Usuarios" Method="Cargar_Credito_Usuarios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Plata" Parameter="plata" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ID_Descripcion" Parameter="iD_Descripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Premio_1" Parameter="premio_1" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Premio_2" Parameter="premio_2" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comentarios_De_Los_Usuarios" Method="Comentarios_De_Los_Usuarios">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Determinar_Si_Es_Ejercicio_O_Video_Y_Pone_Uno_O_Dos_Botones" Method="Determinar_Si_Es_Ejercicio_O_Video_Y_Pone_Uno_O_Dos_Botones">
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Mostrar_DataList_De_Productos_En_El_Buscador_Inicial" Method="Mostrar_DataList_De_Productos_En_El_Buscador_Inicial">
    <Parameter Name="Profesor" Parameter="profesor" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Colegio" Parameter="colegio" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Materia" Parameter="materia" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.Mostrar_DataList_De_Productos_Similares_X_Enunciado" Method="Mostrar_DataList_De_Productos_Similares_X_Enunciado">
    <Parameter Name="Enunciado_1" Parameter="enunciado_1" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Enunciado_2" Parameter="enunciado_2" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.Mostrar_DataList_De_Productos_Similares_X_Ficha" Method="Mostrar_DataList_De_Productos_Similares_X_Ficha">
    <Parameter Name="Profesor" Parameter="profesor" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Colegio" Parameter="colegio" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Materia" Parameter="materia" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="NVarChar(150)" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.Ver_Si_La_Explicacion_Fue_Comprado_Desde_Mis_Ejercicios" Method="Ver_Si_La_Explicacion_Fue_Comprado_Desde_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Mostrar_El_Panel_De_Control_Del_Usuario" Method="Mostrar_El_Panel_De_Control_Del_Usuario">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="Mostrar_El_Panel_De_Control_Del_UsuarioResult">
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activacion_De_Usuarios" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_De_Skype" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Numero_De_Celular" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Modelo_De_Celular" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_De_Alta" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Mostrar_Los_Movimientos_Realizados_X_El_Usuario" Method="Mostrar_Los_Movimientos_Realizados_X_El_Usuario">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="Mostrar_Los_Movimientos_Realizados_X_El_UsuarioResult">
      <Column Name="Fecha_Del_Movimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_De_Movimiento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Plata_Debe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Plata_Haber" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Obtener_Credito_De_La_Tarjeta" Method="Obtener_Credito_De_La_Tarjeta">
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Credito" Parameter="credito" Type="System.Decimal" DbType="Decimal(18,2)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Obtener_El_Credito_Del_Usuario" Method="Obtener_El_Credito_Del_Usuario">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Credito_De_Usuario" Parameter="credito_De_Usuario" Type="System.Decimal" DbType="Decimal(18,2)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_DataList_Del_Inicio" Method="Paginado_DataList_Del_Inicio">
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_DataList_Enunciado" Method="Paginado_DataList_Enunciado">
    <Parameter Name="Enunciado_1" Parameter="enunciado_1" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Enunciado_2" Parameter="enunciado_2" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_DataList_Ficha" Method="Paginado_DataList_Ficha">
    <Parameter Name="Profesor" Parameter="profesor" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Colegio" Parameter="colegio" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Materia" Parameter="materia" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_Mis_Ejercicios" Method="Paginado_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_Mis_Explicaciones" Method="Paginado_Mis_Explicaciones">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Pedido_Prestamo_SOS" Method="Pedido_Prestamo_SOS">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Recuperar_Contrasena" Method="Recuperar_Contrasena">
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" Direction="InOut" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Reenviar_Activacion_Al_Usuario" Method="Reenviar_Activacion_Al_Usuario">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" Direction="InOut" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Registrar_Usuario" Method="Registrar_Usuario">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Bonificacion_X_Registrarse" Method="Bonificacion_X_Registrarse">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Bonificacion_X_Carga" Method="Bonificacion_X_Carga">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Plata" Parameter="plata" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Premio_2" Parameter="premio_2" Type="System.Decimal" DbType="Decimal(18,2)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Bonificacion_X_Cantidad" Method="Bonificacion_X_Cantidad">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paginado_DataList_Desde_El_Buscador_Inicial" Method="Paginado_DataList_Desde_El_Buscador_Inicial">
    <Parameter Name="Profesor" Parameter="profesor" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Colegio" Parameter="colegio" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Materia" Parameter="materia" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Cargar_Premio_En_La_Proxima_Recarga" Method="Cargar_Premio_En_La_Proxima_Recarga">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Plata" Parameter="plata" Type="System.Decimal" DbType="Money" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Premio_1" Parameter="premio_1" Type="System.Decimal" DbType="Decimal(18,2)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Ver_Si_El_Ejercicio_Fue_Comprado_Desde_Mis_Ejercicios" Method="Ver_Si_El_Ejercicio_Fue_Comprado_Desde_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Mostrar_DataList_En_Mis_Ejercicios" Method="Mostrar_DataList_En_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="Mostrar_DataList_En_Mis_EjerciciosResult">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ejercicio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Explicacion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Mostrar_DataList_En_Mis_Explicaciones" Method="Mostrar_DataList_En_Mis_Explicaciones">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="Mostrar_DataList_En_Mis_ExplicacionesResult">
      <Column Name="ID_Ejercicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Compra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dias_Que_Restan_Para_Usar_El_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_De_Vencimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Permitir_Uso_Del_Profesor_On_Line" Method="Permitir_Uso_Del_Profesor_On_Line">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Ejercicio_Desde_DataList_Inicial" Method="Comprar_Ejercicio_Desde_DataList_Inicial">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Video_Desde_El_DataList_Inicial" Method="Comprar_Video_Desde_El_DataList_Inicial">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Ejercicio_Desde_Mis_Ejercicios" Method="Comprar_Ejercicio_Desde_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Ejercicio_Desde_Pagina_Ficha" Method="Comprar_Ejercicio_Desde_Pagina_Ficha">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Ejercicio_Para_Imprimir" Method="Comprar_Ejercicio_Para_Imprimir">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Explicacion_Desde_DataList_Inicial" Method="Comprar_Explicacion_Desde_DataList_Inicial">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Mi_Ejercicio_Personalizado" Method="Comprar_Mi_Ejercicio_Personalizado">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Archivo_Adjunto" Parameter="archivo_Adjunto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Archivo_Ficha" Parameter="archivo_Ficha" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Archivo_Enunciado" Parameter="archivo_Enunciado" Type="System.String" DbType="NVarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Mostrar_DataList_Del_Inicio" Method="Mostrar_DataList_Del_Inicio">
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.Comprar_Ejercicio_Desde_Pagina_Enunciado" Method="Comprar_Ejercicio_Desde_Pagina_Enunciado">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Explicacion_Desde_Mis_Ejercicios" Method="Comprar_Explicacion_Desde_Mis_Ejercicios">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Explicacion_Desde_Pagina_Enunciado" Method="Comprar_Explicacion_Desde_Pagina_Enunciado">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Explicacion_Desde_Pagina_Ficha" Method="Comprar_Explicacion_Desde_Pagina_Ficha">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Ejercicio" Parameter="iD_Ejercicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Mi_Ejercicio_Personalizado_Desde_Enunciado" Method="Comprar_Mi_Ejercicio_Personalizado_Desde_Enunciado">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Adjunto" Parameter="adjunto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Archivo" Parameter="archivo" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Nombre_Adjunto" Parameter="nombre_Adjunto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Explicacion_Pedida" Parameter="explicacion_Pedida" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Existencia_Enunciado" Parameter="existencia_Enunciado" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Mi_Ejercicio_Personalizado_Desde_Ficha" Method="Comprar_Mi_Ejercicio_Personalizado_Desde_Ficha">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Adjunto" Parameter="adjunto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Archivo" Parameter="archivo" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Nombre_Adjunto" Parameter="nombre_Adjunto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Explicacion_Pedida" Parameter="explicacion_Pedida" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Existencia_Enunciado" Parameter="existencia_Enunciado" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Mi_Explicacion_Personalizada_Desde_Enunciado" Method="Comprar_Mi_Explicacion_Personalizada_Desde_Enunciado">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Adjunto" Parameter="adjunto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Archivo" Parameter="archivo" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Nombre_Adjunto" Parameter="nombre_Adjunto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Ejercicio_Pedido" Parameter="ejercicio_Pedido" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Existencia_Enunciado" Parameter="existencia_Enunciado" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Comprar_Mi_Explicacion_Personalizada_Desde_Ficha" Method="Comprar_Mi_Explicacion_Personalizada_Desde_Ficha">
    <Parameter Name="ID_Usuario" Parameter="iD_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IP_Address" Parameter="iP_Address" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ID_Empresa" Parameter="iD_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Adjunto" Parameter="adjunto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Archivo" Parameter="archivo" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Nombre_Adjunto" Parameter="nombre_Adjunto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Ejercicio_Pedido" Parameter="ejercicio_Pedido" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Existencia_Enunciado" Parameter="existencia_Enunciado" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
</Database>